services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data               2
    networks:
      - teacoder

volumes:
  postgres_data:
networks:
  teacoder: