services:
  postgres:
    container_name: teacoder-pg
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data               2
    networks:
      - teacoder

  pgadmin:
    container_name: teacoder-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .docker.env
    ports:
      - "9090:90"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - teacoder

volumes:
  postgres_data:
  pgadmin_data:
networks:
  teacoder: